### ISSUE TITLE
Wiki is gone?

### ISSUE THREAD

**Issue by jalgroy** [NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver#358]
Hi!
If I'm not mistaken there was a Github wiki in this repo with examples of transmitting/receiving using this driver, but now it seems to be gone. Are the examples available anywhere else?

Thanks.

**Comment by hubertmis** [comment]
@jalgroy , Github wiki was outdated. Because of that we decided to disable it. At the moment we are preparing up-to-date documentation.

> Are the examples available anywhere else?

Not at the moment. The examples were outdated and not working correctly. I recommend to use API documentation from https://github.com/NordicSemiconductor/nRF-IEEE-802.15.4-radio-driver/blob/master/src/nrf_802154.h until high-level documentation with examples is ready.

**Comment by hubertmis** [comment]
The documentation is back online. Please check this link: https://infocenter.nordicsemi.com/index.jsp?topic=%2Fstruct_drivers%2Fstruct%2Fradio_driver_latest.html

**Comment by jalgroy** [comment]
Thanks!
